# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'CI: run code format tests'
run-name: Check source code with linters and formatters

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize]

  merge_group:
    types:
      - checks_requested

  workflow_dispatch:
    inputs:
      debug:
        description: 'Run with debugging options'
        type: boolean
        default: true

permissions: read-all

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}

jobs:
  find-changes:
    name: Find changed files
    uses: ./.github/workflows/_find_changes.yaml
    secrets: inherit

  run-tests:
    if: ${{needs.find-changes.outputs.python == 'true' || inputs.debug}}
    name: Run tests
    needs: find-changes
    runs-on: ubuntu-24.04
    continue-on-error: true
    timeout-minutes: 30
    env:
      # Add xtrace to SHELLOPTS for all Bash scripts when doing debug runs.
      SHELLOPTS: ${{inputs.debug && 'xtrace' || '' }}
    steps:
      - if: >-
          ${{needs.find-changes.outputs.python == 'false'
            && github.event_name != 'workflow_dispatch'}}
        name: Exit early if there were no changes to code files
        run: exit 0

      - name: Check out a copy of the git repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # Need the full git history for format-incremental.
          fetch-depth: 0

      - name: Set up Python with caching of pip dependencies
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.13'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            dev-requirements.txt

      - name: Install qsim development dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Check Python file format
        run: check/format-incremental

  report-results:
    if: always()
    name: ${{github.workflow}}
    needs: run-tests
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - name: Exit with an appropriate status code
        run: |
          result="${{needs.run-tests.result}}"
          [[ "$result" == "success" || "$result" == "skipped" ]]
