# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'CI: run sanitizer tests'
run-name: Test with address and memory sanitizers

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize]

  merge_group:
    types:
      - checks_requested

  workflow_dispatch:
    inputs:
      debug:
        description: 'Run with debugging options'
        type: boolean
        default: true

permissions: read-all

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}

jobs:
  find-changes:
    name: Find changed files
    uses: ./.github/workflows/_find_changes.yaml
    secrets: inherit

  run-tests:
    if: ${{needs.find-changes.outputs.code == 'true' || inputs.debug}}
    name: Run tests
    needs: find-changes
    runs-on: ubuntu-24.04
    continue-on-error: true
    timeout-minutes: 30
    strategy:
      matrix:
        # Memory and address sanitizers.
        sanitizer_opt: [msan, asan]
    env:
      use-verbose: ${{inputs.debug}}
    steps:
      - if: >-
          ${{needs.find-changes.outputs.code == 'false'
            && github.event_name != 'workflow_dispatch'}}
        name: Exit early if there were no changes to code files
        run: exit 0

      - name: Check out a copy of the git repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1
          submodules: recursive

      - uses: bazel-contrib/setup-bazel@4fd964a13a440a8aeb0be47350db2fc640f19ca8 # 0.15.0
        with:
          disk-cache: ${{github.workflow}}
          bazelisk-cache: true
          external-cache: true
          repository-cache: true

      - name: Set up Python with caching of pip dependencies
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        id: setup
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            dev-requirements.txt

      - name: Install qsim development dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Run C++ tests
        run: |
          bazel test \
              --config=avx \
              --config=openmp \
              --config=${{matrix.sanitizer_opt}} \
              ${{env.use-verbose && '--config=verbose'}} \
              tests:all

  report-results:
    if: always()
    name: ${{github.workflow}}
    needs: run-tests
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - name: Exit with an appropriate status code
        run: |
          result="${{needs.run-tests.result}}"
          [[ "$result" == "success" || "$result" == "skipped" ]]
